name: NBA Web Scraper

on:
  schedule:
    ## Run every day at 12:00 PM EST (5:00 PM UTC)
    - cron: "0 17 * * *"
  workflow_dispatch: # Allow for manual triggers


jobs:
  run-nba-scraper:
    runs-on: ubuntu-latest  # Use Ubuntu for the runner
    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          # Install dependencies from requirements.txt
          pip install --upgrade pip
          pip install -r requirements.txt

          # Install Playwright dependencies
          python -m playwright install

      # Step 4: Run the Python script
      - name: Run NBA web scraper
        run: |
          # Navigate to the webscraping directory
          cd webscraping

          # Run the web scraper script
          python nba_webscraper.py

      # Step 5: Commit and push the CSV file using PAT
      - name: Commit and push CSV file
        run: |
          # Navigate to the parent directory where the CSV file is saved
          cd nba_saved_csv

          # Get the current date in MM_DD_YYYY format
          current_date=$(date +'%m_%d_%Y')
          csv_file="nba_betting_data_${current_date}.csv"
          
          # Check if the CSV file exists and commit it
          if [ -f "$csv_file" ]; then
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"

            # Configure Git to use the GITHUB_TOKEN for authentication
            git remote set-url origin https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

            # Add the file
            git add "$csv_file"
            git commit -m "Add NBA betting data for ${current_date}"
            git push
          else
            echo "CSV file not found, skipping commit."
          fi
