name: NBA Web Scraper

on:
  schedule:
    # Run daily at noon (12:00 PM) UTC
    - cron: "* * * * *"
  workflow_dispatch: # Allow for manual triggers

jobs:
  run-nba-scraper:
    runs-on: ubuntu-latest  # Use Ubuntu for the runner
    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          # Install dependencies from requirements.txt
          pip install --upgrade pip
          pip install -r requirements.txt

          # Install Playwright dependencies
          python -m playwright install

      # Step 4: Run the Python script
      - name: Run NBA web scraper
        run: |
          # Navigate to the webscraping directory
          cd webscraping

          # Run the web scraper script
          python nba_webscraper.py
